"""ddd: operation

Revision ID: c96c0782e793
Revises: de55f85999b2
Create Date: 2025-12-01 11:59:03.220477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c96c0782e793"
down_revision: Union[str, Sequence[str], None] = "de55f85999b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("routing_id", sa.BigInteger(), nullable=False),
        sa.Column("seq_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("standard_time_s", sa.Integer(), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("tool_requirements", sa.JSON(), nullable=True),
        sa.Column("skill_requirements", sa.JSON(), nullable=True),
        sa.Column("setup_group", sa.String(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["routing_id"], ["routings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_operations_id"), "operations", ["id"], unique=False)
    op.create_index(
        op.f("ix_operations_tenant_id"), "operations", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operations_tenant_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_id"), table_name="operations")
    op.drop_table("operations")
    # ### end Alembic commands ###
