"""ddd: routing

Revision ID: de55f85999b2
Revises: 40f25d4ef325
Create Date: 2025-12-01 11:47:58.628506

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de55f85999b2"
down_revision: Union[str, Sequence[str], None] = "40f25d4ef325"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "routings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_routings_id", "routings", ["id"])
    op.create_index("ix_routings_product_id", "routings", ["product_id"])
    op.create_index("ix_routings_tenant_id", "routings", ["tenant_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_routings_tenant_id", table_name="routings")
    op.drop_index("ix_routings_product_id", table_name="routings")
    op.drop_index("ix_routings_id", table_name="routings")
    op.drop_table("routings")
    # ### end Alembic commands ###
